upload

diff --git a/drunner/servicerunner b/drunner/servicerunner
--- a/drunner/servicerunner
+++ b/drunner/servicerunner
@@ -80,24 +80,26 @@ function main {
          obliterate_start)
             docker stop ${SERVICENAME} 2>&1
             docker rm ${SERVICENAME} 2>&1
+            exit 0
             ;;
 
          uninstall_start)
             docker stop ${SERVICENAME} 2>&1
             docker rm ${SERVICENAME} 2>&1
+            exit 0
             ;;
 
          #--- custom commands
 
          configure)
-         [-v BUCKET] || die "Undefined: BUCKET"
-         [-v S3KEY]  || die "Undefined: S3KEY"
-         [-v S3SECRET] || die "Underfined: S3SECRET"
-         cat <<EOF >/config/upload.sh
-BUCKET=${BUCKET}
-S3KEY=${S3KEY}
-S3SECRET=${S3SECRET}"
-EOF
+         if [ -z "${S3KEY}" ]; then showhelp ; die "Missing S3KEY." ; fi
+         if [ -z "${S3SECRET}" ]; then showhelp ; die "Missing S3SECRET." ; fi
+         if [ -z "${BUCKET}" ]; then showhelp ; die "Missing BUCKET." ; fi
+
+         docker run -it --name="${SERVICENAME}-${COMMAND}" -h "${HOSTNAME}" -e "S3KEY=${S3KEY}" -e "S3SECRET=${S3SECRET}" -e "BUCKET=${BUCKET}" "${DOCKEROPTS[@]}" "${IMAGENAME}" configure "$@"
+         local RVAL=$?
+         docker rm "${SERVICENAME}-${COMMAND}" >/dev/null
+         if [ $RVAL -ne 0 ]; then die "${SERVICENAME} ${COMMAND} failed." ; fi
          ;;
 
          start)
